# Generated by Django 3.0.4 on 2020-03-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tugas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tugas',
            old_name='siswa',
            new_name='user',
        ),
    ]
