# Generated by Django 3.0.4 on 2020-03-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200309_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tugas',
            old_name='user',
            new_name='siswa',
        ),
    ]
